- name: Create elastic service
  template:
    src: elasticsearch.service.j2
    dest: /etc/systemd/system/elasticsearch.service
  become: yes

- name: flush handlers
  meta: flush_handlers

- name: Launch system reload
  debug:
    msg: "Reload systemd conf"
  notify:
    - "Reload systemd conf"

- name: Starting elastic
  service:
    name: elasticsearch.service
    state: started