---
- name: Verify your toolbox version
  become_user: root
  become: yes
  shell: |
    awk -F "|" '{print $2}' /apps/toolboxes/version
  register: version
  delegate_to: "{{ inventory_hostname }}"
  ignore_errors: yes
  ignore_unreachable: yes

- name:
  inventairetoolbox:
    host: "{{ inventory_hostname }}"
    ansible_host: "{{ ansible_host }}"
    env: "{{ env }}"
    version: " {{ version.stdout }}"
  delegate_to: localhost