apiVersion: v1
kind: Service
metadata:
  name: flask-portail-tech-service
spec:
  selector:
    app: portail-tech
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 8000
  type: LoadBalancer
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portail-tech
spec:
  selector:
    matchLabels:
      app: portail-tech
  replicas: 1
  template:
    metadata:
      labels:
        app: portail-tech
      spec:
        containers:
        - name: portail-tech
          image: portail-tech:1.0
          imagePullPolocy: Always
          ports:
            - containerPort: 5000
